# Generated by Django 2.2.10 on 2020-03-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('published_at', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('desciption', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
                ('url_to_image', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=300)),
                ('source', models.CharField(max_length=300)),
            ],
        ),
    ]
